### ISSUE TITLE
Merge with Material?

### ISSUE THREAD

**Issue by squidfunk** [mberneti/mkdocs-rtl#2]
Stumbled across this project by accident - this is actually pretty interesting. Would love to see RTL support in [Material for MkDocs](squidfunk.github.io/mkdocs-material/). Would you mind isolating the changes you made into a PR and I would integrate it?

**Comment by mberneti** [comment]
Thank you.
Unfortunately, I don't have enough time to do that.

**Comment by squidfunk** [comment]
RTL support was implemented in https://github.com/squidfunk/mkdocs-material/commit/01c9aa5e1198da1da97186976630cb9f46b482f5 and released with [2.5.0](https://github.com/squidfunk/mkdocs-material/releases/tag/2.5.0)

**Comment by mberneti** [comment]
Great job, well done! @squidfunk
